import React, { useCallback, useState } from 'react';
import {
  AdminShell, Card, CardHeader, CardFooterNote, SegmentedFilter, Button,
  Loading, Empty, MicroLabel, Badge,
} from '../../design';
import { adminNav } from '../../design/nav';
import { getFeedback, updateFeedback } from '../services/adminService';
import { useAdminData } from '../useAdminData';

/**
 * What learners have reported, as a queue rather than an archive.
 *
 * It opens on what has not been dealt with, because a screen that opens on
 * everything ever received is one nobody works through — and a report nobody
 * works through is the same as no report. Each row carries the context the
 * learner's screen had at the time, so a bad quiz question can be judged here
 * without a reply-and-ask cycle.
 *
 * Quiz questions are generated by a model and can be wrong. This is the only
 * route by which anyone finds out which ones.
 */
const FILTERS = ['new', 'actioned', 'dismissed', 'all'];

const KIND_LABEL = {
  question: 'Quiz question',
  roadmap: 'Roadmap',
  general: 'General',
};

/** The context fields worth reading, in the order they make sense. */
const CONTEXT_ORDER = [
  ['question', 'Question'],
  ['givenAnswer', 'They answered'],
  ['correctAnswer', 'Marked correct'],
  ['topic', 'Topic'],
  ['difficulty', 'Difficulty'],
  ['targetRole', 'Track'],
  ['weekNumber', 'Week'],
  ['skills', 'Skills'],
  ['page', 'Page'],
];

const when = (iso) => (iso ? new Date(iso).toLocaleDateString('en-GB', {
  day: '2-digit', month: 'short', year: 'numeric',
}) : '—');

const Feedback = () => {
  const [filter, setFilter] = useState('new');
  const [busyId, setBusyId] = useState(null);

  const loader = useCallback(() => getFeedback(filter), [filter]);
  const { data, loading, error, reload } = useAdminData(loader);

  const items = data?.items || [];
  const counts = data?.counts || { new: 0, actioned: 0, dismissed: 0 };

  const setStatus = async (id, status) => {
    setBusyId(id);
    try {
      await updateFeedback(id, { status });
      await reload();
    } finally {
      setBusyId(null);
    }
  };

  return (
    <AdminShell items={adminNav} title="Feedback">
      <Card>
        <CardHeader
          label={`${counts.new} waiting`}
          right={<SegmentedFilter options={FILTERS} value={filter} onChange={setFilter} />}
        />

        {loading ? (
          <Loading />
        ) : error ? (
          <Empty action={<Button onClick={reload}>Try again</Button>}>{error}</Empty>
        ) : items.length === 0 ? (
          <Empty>
            {filter === 'new'
              ? 'Nothing waiting. Reports from learners land here.'
              : `No ${filter} feedback.`}
          </Empty>
        ) : (
          items.map((item, i) => (
            <div
              key={item._id}
              style={{
                padding: '18px 24px',
                borderBottom: i === items.length - 1 ? 'none' : '1px solid var(--color-line-soft)',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' }}>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
                  <span style={{ fontSize: 15, fontWeight: 600, color: 'var(--color-ink)' }}>
                    {KIND_LABEL[item.kind] || item.kind}
                  </span>
                  <span style={{ fontSize: 13.5, color: 'var(--color-text-3)' }}>{item.summary}</span>
                  {item.status !== 'new' && <Badge tone="muted">{item.status}</Badge>}
                </div>
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12.5, color: 'var(--color-text-4)' }}>
                  {when(item.createdAt)}
                </span>
              </div>

              <p style={{ fontSize: 15, color: 'var(--color-ink)', lineHeight: 1.55, margin: '10px 0 0' }}>
                {item.message}
              </p>

              {/* The state the learner's screen was in. Without it, judging a
                  report means asking them which question they meant. */}
              {Object.keys(item.context || {}).length > 0 && (
                <div style={{ marginTop: 12, padding: '12px 14px', background: 'var(--color-surface-active)' }}>
                  {CONTEXT_ORDER.filter(([key]) => item.context[key]).map(([key, label]) => (
                    <div key={key} style={{ display: 'flex', gap: 12, marginBottom: 4, flexWrap: 'wrap' }}>
                      <MicroLabel size={10} tracking="0.12em" color="var(--color-text-4)" style={{ width: 110, flexShrink: 0 }}>
                        {label}
                      </MicroLabel>
                      <span style={{ fontSize: 13.5, color: 'var(--color-text-2)', flex: 1, minWidth: 200 }}>
                        {item.context[key]}
                      </span>
                    </div>
                  ))}
                </div>
              )}

              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 12, flexWrap: 'wrap' }}>
                <span style={{ fontSize: 13, color: 'var(--color-text-4)' }}>
                  {item.from ? `${item.from.name || 'Someone'} · ${item.from.email}` : 'Account since deleted'}
                </span>
                <span style={{ flex: 1 }} />
                {item.status !== 'actioned' && (
                  <Button
                    variant="secondary"
                    style={{ padding: '7px 14px', fontSize: 13.5 }}
                    disabled={busyId === item._id}
                    onClick={() => setStatus(item._id, 'actioned')}
                  >
                    Actioned
                  </Button>
                )}
                {item.status !== 'dismissed' && (
                  <Button
                    variant="quiet"
                    disabled={busyId === item._id}
                    onClick={() => setStatus(item._id, 'dismissed')}
                  >
                    Dismiss
                  </Button>
                )}
                {item.status !== 'new' && (
                  <Button
                    variant="quiet"
                    disabled={busyId === item._id}
                    onClick={() => setStatus(item._id, 'new')}
                  >
                    Reopen
                  </Button>
                )}
              </div>
            </div>
          ))
        )}

        <CardFooterNote>
          {`${counts.new} waiting · ${counts.actioned} actioned · ${counts.dismissed} dismissed. Deleting an account removes its reports.`}
        </CardFooterNote>
      </Card>
    </AdminShell>
  );
};

export default Feedback;
