import mongoose from 'mongoose';

/**
 * Something a learner told us was wrong, or wanted.
 *
 * The contact form already existed and only sent an email, so a message
 * lived in an inbox and nowhere in the product: nothing could count it,
 * reopen it, or tell whether it had been dealt with. This is the durable
 * version, and it is deliberately narrower — feedback is a report about a
 * specific thing rather than a rating of the product.
 *
 * The point of `context` is that a report arrives already answerable. "This
 * question is wrong" needs a reply asking which one; the same report carrying
 * the question, the answer given and the answer marked correct can be judged
 * on sight. Quiz questions are generated by a model and can be wrong, and
 * this is the only route by which anyone would ever find out which.
 */
const KINDS = ['question', 'roadmap', 'general'];
const STATUSES = ['new', 'actioned', 'dismissed'];

const feedbackSchema = new mongoose.Schema(
    {
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
            index: true,
        },
        kind: { type: String, enum: KINDS, default: 'general', index: true },
        message: { type: String, required: true, trim: true, maxlength: 2000 },

        /**
         * Whatever the screen knew when the report was made.
         *
         * Loose on purpose: a question report carries different fields from a
         * roadmap one, and a schema listing every possible key would be a
         * second place to edit each time a new control is added.
         */
        context: { type: mongoose.Schema.Types.Mixed, default: {} },

        // Triage, so this does not become another table nobody works through.
        status: { type: String, enum: STATUSES, default: 'new', index: true },
        adminNote: { type: String, default: '', maxlength: 2000 },
        resolvedAt: { type: Date, default: null },
    },
    { timestamps: true }
);

feedbackSchema.index({ status: 1, createdAt: -1 });

export const FEEDBACK_KINDS = KINDS;
export const FEEDBACK_STATUSES = STATUSES;

const Feedback = mongoose.model('Feedback', feedbackSchema);

export default Feedback;
