import React, { useState, useEffect, useRef } from 'react';
import { ChevronDown, HelpCircle, Zap, ShieldCheck, BookOpen, CreditCard, UserCircle } from 'lucide-react';
import BackgroundAnimation from '../Assessment/AssesmentDashboard/components/BackgroundAnimation';

const faqs = [
  {
    category: 'General',
    icon: HelpCircle,
    color: 'indigo',
    items: [
      {
        q: 'What is EduPath?',
        a: 'EduPath is an AI-powered career development platform that helps you build skills, take personalised assessments, generate learning roadmaps, and track your professional growth — all in one place.',
      },
      {
        q: 'Who is EduPath for?',
        a: 'EduPath is designed for students, fresh graduates, and working professionals who want to identify skill gaps and follow a structured learning path towards their career goals.',
      },
      {
        q: 'Is EduPath free to use?',
        a: 'Yes! The core features — assessments, roadmaps, and result history — are completely free. Premium features may be introduced in the future.',
      },
    ],
  },
  {
    category: 'Assessments',
    icon: BookOpen,
    color: 'cyan',
    items: [
      {
        q: 'How does the AI assessment work?',
        a: 'After you select a topic, our AI generates a set of multiple-choice questions tailored to that subject. Your answers are evaluated instantly, and a detailed performance report with a personalised roadmap is produced.',
      },
      {
        q: 'Can I retake an assessment?',
        a: 'Absolutely. You can retake any assessment as many times as you like. Each attempt is saved separately so you can track your progress over time.',
      },
      {
        q: 'How long does an assessment take?',
        a: 'Most assessments contain 10–15 questions and take between 5 and 15 minutes depending on the topic and your pace.',
      },
      {
        q: 'Are the questions different each time?',
        a: 'Yes. Questions are dynamically generated by the AI for every new session, so you will rarely see the exact same question set twice.',
      },
    ],
  },
  {
    category: 'AI & Roadmaps',
    icon: Zap,
    color: 'purple',
    items: [
      {
        q: 'What is a learning roadmap?',
        a: 'After completing an assessment, our AI analyses your results and generates a personalised, step-by-step roadmap highlighting the topics you need to focus on to reach your goal.',
      },
      {
        q: 'How accurate is the AI feedback?',
        a: 'The AI is powered by large language models fine-tuned on educational and career data. While it provides high-quality guidance, we recommend treating it as a supplement to, not a replacement for, human mentorship.',
      },
      {
        q: 'Can I re-generate my roadmap?',
        a: 'Yes. You can generate a new roadmap at any time by retaking the assessment or visiting your Roadmap History.',
      },
    ],
  },
  {
    category: 'Account & Privacy',
    icon: UserCircle,
    color: 'teal',
    items: [
      {
        q: 'How do I reset my password?',
        a: 'Click "Forgot Password" on the Sign In page, enter your registered email, and a reset link will be sent to your inbox within a few minutes.',
      },
      {
        q: 'How do I change my password?',
        a: 'Go to Settings from your profile menu, then select the "Security" or "Change Password" section. Enter your current password, then your new password twice to confirm. Changes take effect immediately.',
      },
      {
        q: 'Is my data safe?',
        a: 'Yes. We follow industry-standard encryption practices. Your personal information and assessment data are stored securely and are never sold to third parties.',
      },
      {
        q: 'Can I delete my account?',
        a: 'You can request account deletion from the Settings page. All your data will be permanently removed within 7 business days.',
      },
    ],
  },
];

const colorMap = {
  indigo: {
    icon: 'bg-indigo-500/15 border-indigo-400/30 text-indigo-400',
    badge: 'bg-indigo-500/10 text-indigo-300 border-indigo-500/20',
    open: 'border-indigo-500/40 shadow-indigo-500/10',
    bar: 'bg-indigo-500/30',
  },
  cyan: {
    icon: 'bg-cyan-500/15 border-cyan-400/30 text-cyan-400',
    badge: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/20',
    open: 'border-cyan-500/40 shadow-cyan-500/10',
    bar: 'bg-cyan-500/30',
  },
  purple: {
    icon: 'bg-purple-500/15 border-purple-400/30 text-purple-400',
    badge: 'bg-purple-500/10 text-purple-300 border-purple-500/20',
    open: 'border-purple-500/40 shadow-purple-500/10',
    bar: 'bg-purple-500/30',
  },
  teal: {
    icon: 'bg-teal-500/15 border-teal-400/30 text-teal-400',
    badge: 'bg-teal-500/10 text-teal-300 border-teal-500/20',
    open: 'border-teal-500/40 shadow-teal-500/10',
    bar: 'bg-teal-500/30',
  },
};

const FAQItem = ({ q, a, color, isOpen, onToggle }) => {
  const c = colorMap[color];
  const contentRef = useRef(null);
  const [height, setHeight] = useState(0);

  useEffect(() => {
    if (contentRef.current) {
      setHeight(isOpen ? contentRef.current.scrollHeight : 0);
    }
  }, [isOpen]);

  return (
    <div
      className={`rounded-xl border transition-all duration-350 ${
        isOpen
          ? `border-white/15 ${c.open} shadow-lg bg-white/[0.04]`
          : 'border-white/8 bg-white/[0.02] hover:border-white/15 hover:bg-white/[0.04]'
      }`}
    >
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left group"
      >
        <span className={`text-sm font-medium leading-snug transition-colors duration-200 ${isOpen ? 'text-white' : 'text-gray-300 group-hover:text-white'}`}>
          {q}
        </span>
        <div className={`shrink-0 w-6 h-6 rounded-full flex items-center justify-center transition-all duration-300 ${
          isOpen ? `${c.icon} rotate-180` : 'bg-white/5 border border-white/10'
        }`}>
          <ChevronDown size={13} className={`transition-colors duration-200 ${isOpen ? '' : 'text-gray-500'}`} />
        </div>
      </button>

      {/* Answer — animates to exact measured height */}
      <div
        style={{
          height: `${height}px`,
          overflow: 'hidden',
          transition: 'height 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        }}
      >
        <div ref={contentRef}>
          <div className={`mx-5 mb-3 h-px ${c.bar} transition-opacity duration-300`} style={{ opacity: isOpen ? 1 : 0 }} />
          <p
            className="px-5 pb-5 text-sm text-gray-400 leading-relaxed"
            style={{
              opacity: isOpen ? 1 : 0,
              transform: isOpen ? 'translateY(0)' : 'translateY(-6px)',
              transition: 'opacity 0.25s ease 0.1s, transform 0.25s ease 0.1s',
            }}
          >
            {a}
          </p>
        </div>
      </div>
    </div>
  );
};

const FAQ = () => {
  const [openMap, setOpenMap] = useState({});

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('animate-in');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.12 }
    );
    document.querySelectorAll('[data-animate]').forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, []);

  const toggle = (catIdx, itemIdx) => {
    const key = `${catIdx}-${itemIdx}`;
    setOpenMap(prev => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <div className="min-h-screen bg-black text-white pt-28 pb-24 px-4 relative overflow-hidden">
      <BackgroundAnimation />

      <div className="relative z-10 max-w-3xl mx-auto">
        {/* Header */}
        <div className="text-center mb-14">
          <div
            data-animate
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-medium mb-5"
          >
            <HelpCircle size={13} />
            Help Center
          </div>
          <h1 data-animate style={{transitionDelay: '0.1s'}} className="text-4xl sm:text-5xl font-bold mb-4">
            Frequently Asked{' '}
            <span
              style={{
                background: 'linear-gradient(90deg,#818cf8,#38bdf8)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              Questions
            </span>
          </h1>
          <p data-animate style={{transitionDelay: '0.2s'}} className="text-gray-400 text-base max-w-xl mx-auto leading-relaxed">
            Can't find an answer? Reach out via the{' '}
            <a href="/contact" className="text-indigo-400 hover:text-indigo-300 underline underline-offset-2 transition-colors">
              Contact Us
            </a>{' '}
            page and we'll get back to you within 24 hours.
          </p>
        </div>

        {/* FAQ sections */}
        <div className="space-y-10">
          {faqs.map((section, catIdx) => {
            const c = colorMap[section.color];
            const Icon = section.icon;
            return (
              <div key={catIdx}>
                {/* Section header */}
                <div
                  data-animate
                  style={{ transitionDelay: `${catIdx * 0.08}s` }}
                  className="flex items-center gap-3 mb-4"
                >
                  <div className={`w-8 h-8 rounded-lg border flex items-center justify-center ${c.icon}`}>
                    <Icon size={15} />
                  </div>
                  <span className={`text-xs font-semibold px-2.5 py-1 rounded-full border ${c.badge}`}>
                    {section.category}
                  </span>
                  <div className="flex-1 h-px bg-white/5" />
                </div>

                {/* Items */}
                <div className="space-y-2.5">
                  {section.items.map((item, itemIdx) => (
                    <div
                      key={itemIdx}
                      data-animate
                      style={{ transitionDelay: `${catIdx * 0.08 + itemIdx * 0.07}s` }}
                    >
                      <FAQItem
                        q={item.q}
                        a={item.a}
                        color={section.color}
                        isOpen={!!openMap[`${catIdx}-${itemIdx}`]}
                        onToggle={() => toggle(catIdx, itemIdx)}
                      />
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>

        {/* Bottom CTA */}
        <div
          data-animate
          className="mt-14 text-center backdrop-blur-xl bg-white/[0.03] border border-white/10 rounded-2xl p-8"
        >
          <p className="text-white font-semibold text-lg mb-1">Still have questions?</p>
          <p className="text-gray-400 text-sm mb-5">Our team is happy to help you out.</p>
          <a
            href="/contact"
            className="inline-flex items-center gap-2 px-6 py-2.5 rounded-xl text-sm font-medium text-white transition-all duration-200 hover:scale-105 active:scale-95"
            style={{
              background: 'linear-gradient(135deg, rgba(99,102,241,0.7), rgba(139,92,246,0.7))',
              border: '1px solid rgba(139,92,246,0.35)',
              boxShadow: '0 0 20px rgba(99,102,241,0.25)',
            }}
          >
            Contact Us
          </a>
        </div>
      </div>
    </div>
  );
};

export default FAQ;
