import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'

const SERVICES = [
  {
    icon: '🧠',
    title: 'AI Skill Assessment',
    description:
      'Take adaptive quizzes generated by AI across 50+ tech domains. Every question is tailored to your level — from beginner to advanced.',
    badge: 'Core Feature',
    badgeColor: 'bg-indigo-500/15 border-indigo-500/30 text-indigo-300',
    accent: 'from-indigo-500/20 to-indigo-600/5',
    border: 'border-indigo-500/20 hover:border-indigo-500/50',
    cta: { label: 'Start Assessment', path: '/assessment' },
  },
  {
    icon: '📄',
    title: 'Resume Builder & Parser',
    description:
      'Upload your existing resume or build one from scratch. Our AI parses, enhances, and scores your resume against industry benchmarks.',
    badge: 'Popular',
    badgeColor: 'bg-emerald-500/15 border-emerald-500/30 text-emerald-300',
    accent: 'from-emerald-500/20 to-emerald-600/5',
    border: 'border-emerald-500/20 hover:border-emerald-500/50',
    cta: { label: 'Build Resume', path: '/resume' },
  },
  {
    icon: '📈',
    title: 'Progress Dashboard',
    description:
      'Visualise your quiz history, average scores, improvement trends, and skill coverage over time in a clean personal dashboard.',
    badge: 'Insights',
    badgeColor: 'bg-cyan-500/15 border-cyan-500/30 text-cyan-300',
    accent: 'from-cyan-500/20 to-cyan-600/5',
    border: 'border-cyan-500/20 hover:border-cyan-500/50',
    cta: { label: 'My Profile', path: '/profile' },
  },
  {
    icon: '🗺️',
    title: 'AI Career Roadmap',
    description:
      'Get a personalized step-by-step learning roadmap based on your assessment results, target role, and current skill gaps.',
    badge: 'Coming Soon',
    badgeColor: 'bg-violet-500/15 border-violet-500/30 text-violet-300',
    accent: 'from-violet-500/20 to-violet-600/5',
    border: 'border-violet-500/20 hover:border-violet-500/50',
    cta: null,
  },
  {
    icon: '⚡',
    title: 'Instant Explanations',
    description:
      'Every quiz answer — right or wrong — comes with a detailed AI-generated explanation so you learn in real time, not just test.',
    badge: 'Learning',
    badgeColor: 'bg-yellow-500/15 border-yellow-500/30 text-yellow-300',
    accent: 'from-yellow-500/20 to-yellow-600/5',
    border: 'border-yellow-500/20 hover:border-yellow-500/50',
    cta: { label: 'Try a Quiz', path: '/assessment' },
  },
  {
    icon: '🔍',
    title: 'Skill Gap Analysis',
    description:
      'After each assessment, receive a breakdown of exactly where you stand versus industry expectations — with pinpointed areas to improve.',
    badge: 'Analytics',
    badgeColor: 'bg-rose-500/15 border-rose-500/30 text-rose-300',
    accent: 'from-rose-500/20 to-rose-600/5',
    border: 'border-rose-500/20 hover:border-rose-500/50',
    cta: { label: 'View Results', path: '/profile' },
  },
]

const STATS = [
  { value: '50+', label: 'Tech Domains' },
  { value: '10k+', label: 'Questions Generated' },
  { value: '98%', label: 'Accuracy Rate' },
  { value: 'Free', label: 'To Get Started' },
]

const Services = () => {
  const navigate = useNavigate()

  const LINE1 = 'Tools Built for'
  const LINE2 = 'Career Growth'
  const FULL_TEXT = LINE1 + '\n' + LINE2

  const [typedText, setTypedText] = useState('')
  const [cursorVisible, setCursorVisible] = useState(true)
  const [heroReady, setHeroReady] = useState(false)

  // Typewriter
  useEffect(() => {
    let i = 0
    const interval = setInterval(() => {
      i++
      setTypedText(FULL_TEXT.slice(0, i))
      if (i >= FULL_TEXT.length) {
        clearInterval(interval)
        setHeroReady(true)
      }
    }, 55)
    return () => clearInterval(interval)
  }, [])

  // Blinking cursor — stops when typing finishes
  useEffect(() => {
    if (heroReady) {
      setCursorVisible(false)
      return
    }
    const id = setInterval(() => setCursorVisible(v => !v), 530)
    return () => clearInterval(id)
  }, [heroReady])

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('animate-in')
            observer.unobserve(entry.target)
          }
        })
      },
      { threshold: 0.1 }
    )
    document.querySelectorAll('[data-animate]').forEach((el) => observer.observe(el))
    return () => observer.disconnect()
  }, [])

  return (
    <div className="min-h-screen bg-black text-white font-sans">

      {/* Hero */}
      <section className="pt-32 pb-20 px-6 text-center relative overflow-hidden">
        {/* Glow blobs */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-indigo-600/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-20 right-1/4 w-64 h-64 bg-violet-600/8 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 max-w-4xl mx-auto">
          <span className="inline-block text-xs font-semibold tracking-widest uppercase px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/25 text-indigo-300 mb-6">
            Everything you need
          </span>
          <h1 className="text-4xl md:text-6xl font-black tracking-tight leading-tight mb-6 min-h-[2.6em] md:min-h-[2.2em]">
            {(() => {
              const parts = typedText.split('\n')
              return (
                <>
                  <span className="text-white">{parts[0]}</span>
                  {parts[1] !== undefined && (
                    <>
                      <br />
                      <span className="bg-gradient-to-r from-indigo-400 via-violet-400 to-cyan-400 bg-clip-text text-transparent">
                        {parts[1]}
                      </span>
                    </>
                  )}
                  {!heroReady && (
                    <span
                      style={{
                        display: 'inline-block',
                        width: '3px',
                        height: '0.85em',
                        background: 'rgb(99 102 241)',
                        marginLeft: '4px',
                        verticalAlign: 'middle',
                        borderRadius: '2px',
                        opacity: cursorVisible ? 1 : 0,
                        transition: 'opacity 0.1s',
                      }}
                    />
                  )}
                </>
              )
            })()}
          </h1>
          <p className="text-lg text-slate-400 max-w-2xl mx-auto leading-relaxed">
            EduPath combines AI-powered assessments, smart resume tools, and personalised roadmaps into one seamless platform — completely free to start.
          </p>

          <div className="flex flex-wrap justify-center gap-4 mt-10">
            <button
              onClick={() => navigate('/assessment')}
              className="px-8 py-3.5 rounded-xl font-bold bg-indigo-500/20 border border-indigo-400/30 hover:bg-indigo-500/30 hover:border-indigo-400/60 hover:scale-105 hover:shadow-lg hover:shadow-indigo-500/30 transition-all duration-300 cursor-pointer"
            >
              Start for Free →
            </button>
            <button
              onClick={() => navigate('/about')}
              className="px-8 py-3.5 rounded-xl font-bold bg-white/5 border border-white/15 hover:bg-white/10 hover:border-white/30 hover:scale-105 transition-all duration-300 cursor-pointer"
            >
              Learn More
            </button>
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="py-12 px-6 border-y border-white/5">
        <div className="max-w-4xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
          {STATS.map((s) => (
            <div key={s.label} data-animate className="opacity-0 translate-y-4 transition-all duration-500">
              <p className="text-3xl md:text-4xl font-black bg-gradient-to-br from-white to-slate-400 bg-clip-text text-transparent">
                {s.value}
              </p>
              <p className="text-sm text-slate-500 mt-1">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Services Grid */}
      <section className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 data-animate className="text-3xl md:text-4xl font-bold mb-4 opacity-0 translate-y-4 transition-all duration-500">
              Our Services
            </h2>
            <p data-animate className="text-slate-500 max-w-xl mx-auto opacity-0 translate-y-4 transition-all duration-500" style={{ transitionDelay: '0.1s' }}>
              A full suite of AI-driven tools designed to accelerate your tech career.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {SERVICES.map((service, i) => (
              <div
                key={service.title}
                data-animate
                className={`group relative rounded-2xl border bg-gradient-to-br ${service.accent} ${service.border} p-7 flex flex-col gap-4 opacity-0 translate-y-6 transition-all duration-500 hover:shadow-xl`}
                style={{ transitionDelay: `${i * 0.08}s` }}
              >
                {/* Badge */}
                <span className={`self-start text-[11px] font-semibold px-3 py-1 rounded-full border ${service.badgeColor}`}>
                  {service.badge}
                </span>

                {/* Icon */}
                <span className="text-4xl leading-none">{service.icon}</span>

                {/* Content */}
                <div className="flex-1">
                  <h3 className="text-white font-bold text-lg mb-2">{service.title}</h3>
                  <p className="text-slate-400 text-sm leading-relaxed">{service.description}</p>
                </div>

                {/* CTA */}
                {service.cta ? (
                  <button
                    onClick={() => navigate(service.cta.path)}
                    className="mt-2 self-start text-sm font-semibold text-white/70 hover:text-white flex items-center gap-1.5 transition-colors cursor-pointer"
                  >
                    {service.cta.label}
                    <span className="group-hover:translate-x-1 transition-transform duration-200">→</span>
                  </button>
                ) : (
                  <span className="mt-2 self-start text-sm font-semibold text-slate-600 cursor-default">
                    In Development…
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Banner */}
      <section className="py-24 px-6">
        <div className="max-w-3xl mx-auto text-center">
          <div
            data-animate
            className="rounded-3xl border border-indigo-500/20 bg-gradient-to-br from-indigo-500/10 via-violet-500/5 to-transparent p-12 opacity-0 translate-y-6 transition-all duration-600"
          >
            <h2 className="text-3xl md:text-4xl font-black mb-4">
              Ready to accelerate your career?
            </h2>
            <p className="text-slate-400 mb-8 max-w-lg mx-auto">
              Join thousands of learners using EduPath to identify skill gaps, build standout resumes, and land their dream roles.
            </p>
            <button
              onClick={() => navigate('/assessment')}
              className="px-10 py-4 rounded-xl font-bold bg-indigo-500 hover:bg-indigo-400 hover:scale-105 hover:shadow-xl hover:shadow-indigo-500/40 transition-all duration-300 cursor-pointer text-white"
            >
              Start Free Assessment →
            </button>
          </div>
        </div>
      </section>

    </div>
  )
}

export default Services
