import React from 'react';
import { Link } from 'react-router-dom';
import StartLink from '../../component/StartLink';
import { EditorialShell, StatStrip, OrdinalRow, Button, MicroLabel, type } from '../../design';

/**
 * Spec §7 Marketing · text page.
 *
 * A Newsreader 44px heading over prose at 17px / lh 1.65 in a 680px measure.
 * The figures the old page scattered through feature cards become one
 * full-width mono stat strip.
 *
 * This page had drifted into describing a product we do not ship: an adaptive
 * quiz that does not adapt, roadmaps "generated by large language models" when
 * no model is involved in building one, a portfolio assembled from roadmap
 * projects it has never read, and a plan supposedly withheld until you are
 * assessed. It also contradicted the FAQ, which says the opposite about the AI.
 * Everything here is now something the code actually does — the About page is
 * where someone decides whether to trust the rest of it.
 */
const FIGURES = [
  { label: 'Role tracks', value: 6 },
  { label: 'Assessment instruments', value: 4 },
  { label: 'Portfolio templates', value: 11 },
];

/** Steps 1–7 of ai_service/agents/roadmap_generator.py, in plain words. */
const HOW = [
  {
    title: 'Take the track apart',
    body: 'Your role has a curriculum behind it: every skill in it, what each one depends on, and how many hours it usually takes.',
  },
  {
    title: 'Put it in an order that works',
    body: 'The skills are sorted so nothing arrives before the thing it needs. You cannot be scheduled onto Express in a week where Node is still ahead of you.',
  },
  {
    title: 'Remove what you can already do',
    body: 'Assessment scores shorten a skill or drop it entirely — anything it was a prerequisite for comes with it.',
  },
  {
    title: 'Cost it in your hours, not in weeks',
    body: 'Each skill is sized in hours and adjusted for your experience level, then measured against the hours you said you have.',
  },
  {
    title: 'Cut it into weeks',
    body: 'The running total decides where each week starts and ends, so a week can hold the end of one skill and the start of the next.',
  },
];

const Para = ({ children }) => (
  <p style={{ ...type.prose, margin: '0 0 24px', maxWidth: 680 }}>{children}</p>
);

const SubHeading = ({ children }) => (
  <h2
    style={{
      fontFamily: 'var(--font-display)',
      fontSize: 27,
      fontWeight: 400,
      letterSpacing: '-0.015em',
      lineHeight: 1.2,
      color: 'var(--color-ink)',
      margin: '0 0 14px',
    }}
  >
    {children}
  </h2>
);

const About = () => (
  <EditorialShell>
    <section style={{ padding: '80px 0' }}>
      <MicroLabel size={11} tracking="0.14em" color="var(--color-text-4)" style={{ display: 'block', marginBottom: 16 }}>
        About
      </MicroLabel>

      <h1 style={{ ...type.marketingHeading, margin: '0 0 32px', maxWidth: 720 }}>
        Most learning advice is a list. EduPath produces a schedule.
      </h1>

      <Para>
        The hard part of getting job-ready was never finding material — it is knowing what to do
        next, in what order, and whether the thing you finished last week actually moved you
        forward. EduPath exists to answer those three questions with something you can check.
      </Para>

      <Para>
        You pick one of six roles, say how many hours a week you have, and get a roadmap: every
        skill in that track with a week against it, sorted so nothing appears before its
        prerequisite. Marking a skill done reschedules everything after it. When you are ready to
        apply, your resume is scored against the job description you paste in, and a portfolio site
        is published at a URL you can send someone.
      </Para>

      <Para>
        Taking the skill assessment first is what makes the plan yours rather than the whole
        syllabus. Anything you score well on is shortened or dropped, so the difference between an
        assessed plan and an unassessed one is usually months. You are not blocked from generating
        one either way — a plan built on no information just assumes you are starting from the
        beginning, which for most people is the wrong assumption.
      </Para>

      <StatStrip items={FIGURES} style={{ margin: '8px 0 44px' }} />

      <SubHeading>How a plan is built</SubHeading>
      <Para>
        Five steps, none of them a guess. The same inputs produce the same plan every time, which
        is the whole reason this part is not left to a language model.
      </Para>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 20, margin: '0 0 40px', maxWidth: 680 }}>
        {HOW.map((step, i) => (
          <OrdinalRow key={step.title} ordinal={String(i + 1).padStart(2, '0')} editorial>
            <div style={{ fontSize: 15.5, fontWeight: 500, color: 'var(--color-ink)', marginBottom: 4 }}>
              {step.title}
            </div>
            <div style={{ fontSize: 15, lineHeight: 1.6, color: 'var(--color-text-2)' }}>{step.body}</div>
          </OrdinalRow>
        ))}
      </div>

      <SubHeading>Where the AI sits</SubHeading>
      <Para>
        Not in your roadmap. The order comes from a fixed dependency graph and the timings from
        arithmetic on the hours you gave us, so a plan can always be explained line by line and
        will not quietly change its mind between one visit and the next.
      </Para>
      <Para>
        Language models write the quiz questions, run the mock interview and read your resume.
        That is what makes those specific to you, and it is also why they are occasionally wrong.
        Treat them as a well-informed starting point rather than a verdict, and tell us when one is
        off — that is a bug report we can act on.
      </Para>

      <SubHeading>What the four assessments are for</SubHeading>
      <Para>
        Only one of them changes your plan. The skill assessment is the one the roadmap reads.
        Aptitude and CS fundamentals are deliberately not tied to a role — they are practice, not
        planning input. The mock interview scores how well you explain your work and is reported
        beside your roadmap rather than folded into it, because being able to build something and
        being able to talk about it are different problems.
      </Para>

      <SubHeading>What we keep</SubHeading>
      <Para>
        Your account, your attempts, your roadmaps and anything you have generated. Passwords are
        hashed, never stored as text, and nothing is sold on. Deleting your account removes all of
        it straight away — portfolio sites you have already deployed are hosted separately and stay
        online until you take them down yourself.
      </Para>

      <SubHeading>Who built it</SubHeading>
      <Para>
        EduPath started as a final-year engineering project at CHARUSAT University and is still
        run by the people who built it. If something is broken or wrong, the contact form reaches
        a person.
      </Para>

      <div style={{ display: 'flex', gap: 12, marginTop: 8 }}>
        <StartLink>
          <Button>Start with the assessment</Button>
        </StartLink>
        <Link to="/contact" style={{ textDecoration: 'none' }}>
          <Button variant="secondary">Get in touch</Button>
        </Link>
      </div>
    </section>
  </EditorialShell>
);

export default About;
