import React from 'react';
import { Link } from 'react-router-dom';
import { EditorialShell, StatStrip, Button, MicroLabel, type } from '../../design';

/**
 * Spec §7 Marketing · text page.
 *
 * A Newsreader 44px heading over prose at 17px / lh 1.65 in a 680px measure.
 * The figures the old page scattered through feature cards become one
 * full-width mono stat strip.
 */
const FIGURES = [
  { label: 'Role tracks', value: 6 },
  { label: 'Assessment instruments', value: 4 },
  { label: 'Portfolio templates', value: 11 },
];

const Para = ({ children }) => (
  <p style={{ ...type.prose, margin: '0 0 24px', maxWidth: 680 }}>{children}</p>
);

const SubHeading = ({ children }) => (
  <h2
    style={{
      fontFamily: 'var(--font-display)',
      fontSize: 27,
      fontWeight: 400,
      letterSpacing: '-0.015em',
      lineHeight: 1.2,
      color: 'var(--color-ink)',
      margin: '0 0 14px',
    }}
  >
    {children}
  </h2>
);

const About = () => (
  <EditorialShell>
    <section style={{ padding: '80px 0' }}>
      <MicroLabel size={11} tracking="0.14em" color="var(--color-text-4)" style={{ display: 'block', marginBottom: 16 }}>
        About
      </MicroLabel>

      <h1 style={{ ...type.marketingHeading, margin: '0 0 32px', maxWidth: 720 }}>
        Most learning advice is a list. EduPath produces a schedule.
      </h1>

      <Para>
        The hard part of getting job-ready was never finding material — it is knowing what to do
        next, in what order, and whether the thing you finished last week actually moved you
        forward. EduPath exists to answer those three questions with something you can check.
      </Para>

      <Para>
        You start with an assessment rather than a syllabus. Four instruments — an adaptive skills
        quiz, a timed aptitude test, CS fundamentals, and a spoken AI mock interview — produce one
        profile of where you stand today. Nothing is planned until that profile exists, because a
        plan built on a guess about your level is a plan you will abandon.
      </Para>

      <Para>
        From the profile you get a roadmap: a dependency-sorted sequence of skills with a week
        against each one, sized to the hours you said you have. Finishing a skill reschedules
        everything after it. When you are ready to apply, your resume is scored against the job
        description you paste in, and your portfolio is built from the projects you actually
        completed on the roadmap, then published at a URL you can send someone.
      </Para>

      <StatStrip items={FIGURES} style={{ margin: '8px 0 40px' }} />

      <SubHeading>Where the AI sits</SubHeading>
      <Para>
        Questions, roadmaps and resume feedback are generated by large language models. That makes
        them fast and specific to you, and it also means they are occasionally wrong. Treat the
        output as a well-informed starting point rather than a verdict — the sequence and the
        scheduling are the parts we are confident about.
      </Para>

      <SubHeading>What we keep</SubHeading>
      <Para>
        Your account, your attempts, your roadmaps and anything you have generated. Passwords are
        hashed, never stored as text, and nothing is sold on. Deleting your account removes all of
        it straight away — portfolio sites you have already deployed are hosted separately and stay
        online until you take them down yourself.
      </Para>

      <SubHeading>Who built it</SubHeading>
      <Para>
        EduPath started as a final-year engineering project at CHARUSAT University and is still
        run by the people who built it. If something is broken or wrong, the contact form reaches
        a person.
      </Para>

      <div style={{ display: 'flex', gap: 12, marginTop: 8 }}>
        <Link to="/signup" style={{ textDecoration: 'none' }}>
          <Button>Start with the assessment</Button>
        </Link>
        <Link to="/contact" style={{ textDecoration: 'none' }}>
          <Button variant="secondary">Get in touch</Button>
        </Link>
      </div>
    </section>
  </EditorialShell>
);

export default About;
